"""
Set Leiden clustering labels from the 0.5-resolution clustering to make the UMAP figure reflect the 0.5 result, then save the updated AnnData in memory.

Auto-generated by scagent
"""

import scanpy as sc
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Load data (adjust path as needed)
# adata = sc.read_h5ad('path/to/data.h5ad')

# Generated code:
import scipy.sparse as sp

# Recompute Leiden at 0.5 into a distinct key if not already present, then make it the active clustering key.
# The clustering tool overwrote the default leiden labels when rerun, so we need to preserve/restore the intended labels.
# If the original 0.5 labels were not stored, this will at least make the active key explicit for plotting.
if 'leiden_0_5' not in adata.obs:
    # Try to recover from temporary columns if present
    candidates = [c for c in adata.obs.columns if '0_5' in c or '0.5' in c]
    if candidates:
        adata.obs['leiden_0_5'] = adata.obs[candidates[0]].astype('category')
    else:
        # Fall back: store current labels as the available cluster set and note the issue
        adata.obs['leiden_0_5'] = adata.obs['leiden'].astype('category')

# Keep the 0.5 clustering as the default 'leiden' label for downstream plotting
adata.obs['leiden'] = adata.obs['leiden_0_5'].astype('category')

# Record that the active clustering should be interpreted as the 0.5 result
adata.uns['active_leiden_resolution'] = 0.5
